---

- name: install the hp gpg key
  apt_key:
    url: '{{ item }}'
    state: present
  with_items: '{{ hwraid_apt_hp_keys }}'
  when: ansible_os_family == 'Debian' and
        ansible_devices.sda is defined and
        ansible_devices.sda.vendor is defined and
        ansible_devices.sda.vendor == 'HP'

- name: add the hp apt repository
  apt_repository:
    repo: '{{ hwraid_apt_hp_repository }}'
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian' and
        hwraid_apt_hp_repository is defined and hwraid_apt_hp_repository and
        ansible_devices.sda is defined and
        ansible_devices.sda.vendor is defined and
        ansible_devices.sda.vendor == 'HP'

- name: add the hp yum repository
  yum_repository:
    name: '{{ hwraid_yum_hp_repository.name }}'
    file: '{{ hwraid_yum_hp_repository.file | default(hwraid_yum_hp_repository.name) }}'
    description: '{{ hwraid_yum_hp_repository.description }}'
    baseurl: '{{ hwraid_yum_hp_repository.baseurl | default(omit) }}'
    mirrorlist: '{{ hwraid_yum_hp_repository.mirrorlist | default(omit) }}'
    repo_gpgcheck: '{{ hwraid_yum_hp_repository.repo_gpgcheck | default(omit) }}'
    gpgcheck: '{{ hwraid_yum_hp_repository.gpgcheck | default("yes") }}'
    gpgkey: '{{ hwraid_yum_hp_repository.gpgkey | default(omit) }}'
    enabled: yes
    state: present
    seuser: system_u
    serole: object_r
    setype: system_conf_t
    selevel: s0
  with_items: '{{ hwraid_yum_hp_repository }}'
  when: ansible_os_family == 'RedHat' and
        ansible_devices.sda is defined and
        ansible_devices.sda.vendor is defined and
        ansible_devices.sda.vendor == 'HP'

- name: install hp raid tools
  package:
    name: '{{ hwraid_hp_raid_packages }}'
    state: present
  when: ansible_devices.sda is defined and
        ansible_devices.sda.vendor is defined and
        ansible_devices.sda.vendor == 'HP'

- name: install the hwraid.le-vert.net gpg key
  apt_key:
    url: '{{ item }}'
    state: present
  with_items: '{{ hwraid_apt_le_vert_keys }}'
  when: ansible_os_family == 'Debian' and
        ansible_devices.sda is defined and
        ansible_devices.sda.vendor is defined and
        ansible_devices.sda.vendor == 'IBM'

- name: add the hwraid.le-vert.net apt repository
  apt_repository:
    repo: '{{ hwraid_apt_le_vert_repository }}'
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian' and
        hwraid_apt_le_vert_repository is defined and hwraid_apt_le_vert_repository and
        ansible_devices.sda is defined and
        ansible_devices.sda.vendor is defined and
        ansible_devices.sda.vendor == 'IBM'

- name: install ibm raid tools
  package:
    name: '{{ hwraid_ibm_raid_packages }}'
    state: present
  when: ansible_devices.sda is defined and
        ansible_devices.sda.vendor is defined and
        ansible_devices.sda.vendor == 'IBM'

- name: check if nagios plugin check_raid is installed
  stat:
    path: '{{ hwraid_nagios_plugin_path }}'
  register: hwraid_register_nagios_plugin
  when: hwraid_nagios_plugin_path is defined and hwraid_nagios_plugin_path

- name: check if nagios plugin check_raid has sudo permissions
  stat:
    path: '{{ hwraid_nagios_plugin_sudoers_path }}'
  register: hwraid_register_nagios_plugin_sudoers
  when: hwraid_nagios_plugin_sudoers_path is defined and hwraid_nagios_plugin_sudoers_path

- name: add the nagios user to the sudoers file
  command: "{{ hwraid_nagios_plugin_path }} -S"
  register: hwraid_register_nagios_plugin_command_check_raid
  failed_when: hwraid_register_nagios_plugin_command_check_raid.rc > 1
  when: hwraid_nagios_plugin_path is defined and hwraid_nagios_plugin_path and
        not hwraid_register_nagios_plugin_sudoers.stat.exists and
        hwraid_register_nagios_plugin.stat.exists
